spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/delivery_manegement
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: cahangirzadenurlan043@gmail.com
    password: jsbygnmhtdmogdft
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
